name: Issue Feature
description: Issue template for new feature requests
title: "[Feature]: "
labels: ["feature", "triage"]
assignees:
  - vibhabellutagi19
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the sections below to help us understand your request.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-feature
    attributes:
      label: What Feature?
      description: What feature are you suggesting?
      placeholder: Tell us what you see!
      value: "A new blog coming up!"
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low
        - Medium
        - High
  - type: textarea
    id: due-date
    attributes:
      label: Due Date
      description: When do you need this feature by?
      placeholder: Select a date

